[build]
  publish = "."
  command = "bash scripts/build.sh"

[context.production.environment]
  NODE_ENV = "production"

# You can manage these in the Netlify UI under "Site settings" -> "Environment variables"
# but defining the keys here as placeholders for clarity
[build.environment]
  VITE_FIREBASE_API_KEY = ""
  VITE_FIREBASE_AUTH_DOMAIN = ""
  VITE_FIREBASE_PROJECT_ID = ""
  VITE_FIREBASE_STORAGE_BUCKET = ""
  VITE_FIREBASE_MESSAGING_SENDER_ID = ""
  VITE_FIREBASE_APP_ID = ""
  VITE_FIREBASE_MEASUREMENT_ID = ""
